name: InternLM
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py310hdda0065_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numpy=1.26.2=py310h5f9d8c6_0
  - numpy-base=1.26.2=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - setuptools=68.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.0.2=py310_cu117
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu117
  - urllib3=1.26.18=py310h06a4308_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.2.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - backoff==2.2.1
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.3
      - cachetools==5.3.2
      - chardet==5.2.0
      - chroma-hnswlib==0.7.3
      - chromadb==0.4.15
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - dataclasses-json==0.5.14
      - deprecated==1.2.14
      - einops==0.7.0
      - emoji==2.10.1
      - exceptiongroup==1.2.0
      - fastapi==0.109.0
      - ffmpy==0.3.1
      - filetype==1.2.0
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - google-auth==2.27.0
      - googleapis-common-protos==1.62.0
      - gradio==4.4.0
      - gradio-client==0.7.0
      - greenlet==3.0.3
      - grpcio==1.60.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httptools==0.6.1
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kubernetes==29.0.0
      - langchain==0.0.292
      - langdetect==1.0.9
      - langsmith==0.0.85
      - lxml==5.1.0
      - markdown==3.3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.20.2
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - monotonic==1.6
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nltk==3.8.1
      - numexpr==2.9.0
      - oauthlib==3.2.2
      - onnxruntime==1.17.0
      - opentelemetry-api==1.22.0
      - opentelemetry-exporter-otlp-proto-common==1.22.0
      - opentelemetry-exporter-otlp-proto-grpc==1.22.0
      - opentelemetry-proto==1.22.0
      - opentelemetry-sdk==1.22.0
      - opentelemetry-semantic-conventions==0.43b0
      - orjson==3.9.12
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.0
      - posthog==3.3.4
      - protobuf==4.25.2
      - pulsar-client==3.4.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.6.0
      - pydantic-core==2.16.1
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pypika==0.48.9
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-iso639==2024.1.2
      - python-magic==0.4.27
      - python-multipart==0.0.6
      - pytz==2023.4
      - pyyaml==6.0.1
      - rank-bm25==0.2.2
      - rapidfuzz==3.6.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rpds-py==0.17.1
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.25
      - starlette==0.35.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.1
      - transformers==4.37.2
      - typer==0.9.0
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - unstructured==0.10.30
      - uvicorn==0.27.0.post1
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websocket-client==1.7.0
      - websockets==11.0.3
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.17.0

